### ISSUE TITLE
Support multiple messages per channel (oneOf)

### ISSUE THREAD

**Issue by patrickuhlmann** [asyncapi/java-template#18]
#### Reason/Context

Usually a single channel can process multiple message (e. g. create a song, delete a song, update a song). This is specified using the oneOf property in the message section.

For example
```
channels:
  song.released:
    publish:
      message:
        oneOf:
          - $ref: '#/components/messages/song'
          - $ref: '#/components/messages/deleteSong'
```

#### Description

I adapted your example and used oneOf.

kafka-example.yml
```
asyncapi: 2.3.0
info:
  title: Record Label Service
  version: 1.0.0
  description: This service is in charge of processing music
servers:
  production:
    url: 'my-kafka-hostname:9092'
    protocol: kafka-secure
    description: Production Instance 1
    security:
      - myScram: []
channels:
  song.released:
    publish:
      message:
        oneOf:
          - $ref: '#/components/messages/song'
          - $ref: '#/components/messages/deleteSong'
    subscribe:
      message:
        $ref: '#/components/messages/song'
components:
  securitySchemes:
    myScram:
      type: scramSha512
  messages:
    deleteSong:
      payload:
        type: object
        properties:
          title:
            type: string
            description: Song title
    song:
      payload:
        type: object
        properties:
          title:
            type: string
            description: Song title
          artist:
            type: string
            description: Song artist
          album:
            type: string
            description: Song album
          genre:
            type: string
            description: Primary song genre
          length:
            type: integer
            description: Track length in seconds
```

Then I executed:
```
ag kafka-example.yml @asyncapi/java-template -o ./output -p server=production
```

The result was the following error:
```
Something went wrong:
TypeError: Cannot read property 'uid' of null
    at Demo (C:\...\nodejs\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-template\components\Demo\Demo.js:40:53)
    at index (C:\...\nodejs\node_modules\@asyncapi\generator\node_modules\@asyncapi\java-template\template\index.js:50:11)
    at Object.<anonymous> (C:\.../nodejs\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\src\renderer\template.ts:23:18)
    at step (C:\...\nodejs\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\lib\renderer\template.js:33:23)
    at Object.next (C:\...\nodejs\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\lib\renderer\template.js:14:53)
    at fulfilled (C:\...\nodejs\node_modules\@asyncapi\generator\node_modules\@asyncapi\generator-react-sdk\lib\renderer\template.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The com.ibm.mq.samples.jms.models folder was empty. I would have expected the song and deleteSong Model there.

**Comment by patrickuhlmann** [comment]
I think this should be supported

**Comment by JapuDCret** [comment]
@patrickuhlmann have you found a solution for your `oneOf` use-case?

Mine is pretty similar, one topic - multiple possible message formats.

**Comment by patrickuhlmann** [comment]
No, we are currently hand-writing the code
